### ISSUE TITLE
Changing screen orientation brings weather details

### ISSUE THREAD

**Issue by Clans** [trigor74/weatherviewer#1]
Every time after I change the screen orientation it brings me the details screen. And I have to press Back button twice to return to the main screen. Nexus 5, Android 5.1.

**Comment by trigor74** [comment]
I thought it would be interesting to implement detailed information after rotation to portrait mode.
If low memory it possible produce a bug, when MainActivity is destroyed. Should I remove this functionality?

**Comment by Clans** [comment]
It's unclear behavior to see the other screen of the app after changing the device's orientation.
